server:
    port: 8888
    servlet:
      context-path: /employer/api
spring:
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  jackson:
      serialization:
        write-dates-as-timestamps: false
  
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    com.blueoptima: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: info
  file: /tmp/config/logs/employer-api.log

  

