server:
    port: 8888
    servlet:
      context-path: /employer/api
spring:
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      show-sql: true 
  datasource:
    url: jdbc:postgresql://postgres:5432/employer_api?currentSchema=employer
    username: employer_user
    password: testing
    driver-class-name: org.postgresql.Driver
  jackson:
      serialization:
        write-dates-as-timestamps: false
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    com.blueoptima: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: info
  file: /tmp/config/logs/employer-api.log

  

