version: '3.3'
services:
  postgres:
    container_name: postgres
    image: "postgres:9.6"
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_USER: employer_user
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  app:
    container_name: employer-api
    build: .
    depends_on:
      - postgres
    ports:
      - "5555:8888"

volumes:
  database: