version: '3.3'
services:
  consul:
    image: bitnami/consul:1.7.2
    volumes:
      - consul_data:/bitnami/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
  vault:
    image: "vault:1.3.4"
    hostname: "vault"
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      SKIP_SETCAP: 1
    privileged: true
    restart: always
    ports:
      - "8200:8200" 
volumes:
  consul_data:
    driver: local